on:
  pull_request: {}
  push:
    branches:
    - main
    paths:
    - .github/workflows/semgrep.yml
  schedule:
  # random HH:MM to avoid a load spike on GitHub Actions at 00:00
  - cron: 0 1 * * *
name: Semgrep
jobs:
  buildGradleLockFile: 
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build Dependency Tree
        run: gradle dependencies --write-locks
      - name: Upload Dependency Tree Artifact     
        uses: actions/upload-artifact@v3
        with:
          name: gradlelockfile
          path: gradle.lockfile

  semgrep:
    needs: buildGradleLockFile
    name: Scan
    runs-on: ubuntu-20.04
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: returntocorp/semgrep
    steps:
      - uses: actions/checkout@v3
      - name: Download artifact from previous job
        uses: actions/download-artifact@v3
        with:
          name: gradlelockfile
      - run: echo "Event type is ${{ github.event_name }}"
      - name: Execute Commands for Push Event
        if: steps.check_event.outputs.event_name == 'push'
        run: |
          echo "This is a push event"
          semgrep ci --oss-only
  
      - name: Execute Commands for Schedule Event
        if: steps.check_event.outputs.event_name == 'schedule'
        run: |
          echo "This is a scheduled event"
          semgrep ci
